AWSTemplateFormatVersion: '2010-09-09'
Description: A basic CloudFormation template for launching an EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0a21e01face015dd9
      KeyName: learning-key
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - sg-0463d0421efd0f6f4
      Tags:
        - Key: Name
          Value: "cloudformation-test"

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
