AWSTemplateFormatVersion: '2010-09-09'
Description: A basic CloudFormation template for launching an EC2 instance with S3 and DynamoDB full access.

Resources:
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  EC2Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: EC2S3DynamoDBFullAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:*
          - dynamodb:*
          Resource: "*"
      Roles:
      - !Ref EC2Role

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: "/"
      Roles:
      - !Ref EC2Role

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0a21e01face015dd9
      KeyName: learning-key
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - sg-0463d0421efd0f6f4
      Tags:
        - Key: Name
          Value: "cloudformation-test"
      IamInstanceProfile: !Ref EC2InstanceProfile

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
